// js/vue/examples/3/src/components/app/Loader.vue
<template>
  <div class="app-loader">
    <div class="preloader-wrapper active">
      <div class="spinner-layer" :class="color">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div>
        <div class="gap-patch">
          <div class="circle"></div>
        </div>
        <div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    computed: {
      // меняем цвет loader
      color() {
        const colors = ['spinner-red-only', 'spinner-blue-only', 'spinner-green-only'];

        return colors[Math.floor(Math.random() * 3)]; // по случайному индексу
      },
    },
  };
</script>

// JS/React/Examples/#7_mern/client/src/components/Loader.js
import React from 'react'

export const Loader = () => (
  <div style={ { display: 'flex', justifyContent: 'center', paddingTop: '2rem' } }>
    <div className="preloader-wrapper active">
      <div className="spinner-layer spinner-red-only">
        <div className="circle-clipper left">
          <div className="circle"/>
        </div>
        <div className="gap-patch">
          <div className="circle"/>
        </div>
        <div className="circle-clipper right">
          <div className="circle"/>
        </div>
      </div>
    </div>
  </div>
)
