// JS/Vue/Examples/#2/components/TodoItem.vue
<template>
    <li>
        <span :class="{done: todo.completed}">
            <input type="checkbox" @change="todo.completed = !todo.completed"><!-- обработчик события change-->
            <strong>{{ index + 1 }}</strong>
            {{ todo.title | uppercase }}
        </span>

        <button class="rm"
                @click="$emit('remove-todo', todo.id)"
        >&times;</button>
    </li>
</template>

<script>
    export default {
        props: {
            todo: {
                type: Object,
                required: true
            },
            index: Number
        },
        filters: {
            uppercase(value) {
                return value.toUpperCase();
            }
        }
    }
</script>

<style scoped>
    li {
        border: 1px solid #ccc;
        display: flex;
        justify-content: space-around;
        padding: .5rem 2rem;
        margin-bottom: 1rem;
    }

    .rm {
        background: red;
        color: #fff;
        border-radius: 50%;
        font-weight: bold;
    }

    input {
        margin-right: 1rem;
    }

    .done {
        text-decoration: line-through;
    }
</style>

// JS/React/Examples/Suspense/src/Todo/TodoItem.js
import React, {useContext} from 'react'
import PropTypes from 'prop-types'
import Context from '../context'

const styles = {
	li: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '.5rem 1rem',
		border: '1px solid #ccc',
		borderRadius: '4px',
		marginBottom: '.5rem'
	},
	input: {
		marginRight: '1rem'
	}
}

function TodoItem({todo, index, onChange}) {
	const {removeTodo} = useContext(Context)
	const classes = []

	if (todo.completed) {
		classes.push('done')
	}

	return (
		<li style={styles.li}>
      <span className={classes.join(' ')}>
        <input
	        type='checkbox'
	        checked={todo.completed}
	        style={styles.input}
	        onChange={() => onChange(todo.id)}
        />
        <strong>{index + 1}</strong>
	      &nbsp;
	      {todo.title}
      </span>

			<button className='rm' onClick={removeTodo.bind(null, todo.id)}>
				&times;
			</button>
		</li>
	)
}

TodoItem.propTypes = {
	todo: PropTypes.object.isRequired,
	index: PropTypes.number,
	onChange: PropTypes.func.isRequired
}

export default TodoItem
